# Travis CI - test workflow </doc/dev/ci.md>

os: linux
dist:
  - xenial

addons:
  apt:
    packages:
      - realpath

sudo: false

services:
  - docker

language: shell
#language: python # Use Python build-env for NPM, PIP setup etc.

env:
  matrix: []
  global:
    - secure: "c2g4VSU982GjA7rAoCu5NhjPzRkCRWnvloG7/5weFOy5JRN9G/aVXPL19VZtQiHaz5O37bL2aC2pNL2Z1AXONtimqPpleYQBq4CEz1gMRQ1uNIT4bUopwGOo1zXXUVeMLO2DxRU2oLB0SnP0ENqY9vg47WewPBkdv9WrXwlTFku/sJkJvZu37z6HLHaZXkIQP2NrD0Gd1VrtV6TNkoZBBFQesP6lR9cc5VjtxqrlHP5EKq9fmFvfsukAdpzinmJnE4XhmjnpmRJ+WiLgSg/miKXyLkTN2UWm0iPRoq22QgAOVJj47naKaUiL2P3uB63Ufaddvkhnqhlbi0PQPgqthY5MdTVcGjEq8cYImA9fgilZIt3bQ/fQeNLrzBV7XZfRbtc6BxlXGbI3I5nf+QMxoFcWLodBqOc4njXvc+SiEN7x+nLjVNCTAOo5Hr+6tOzi7dOUu8/rObKAZm1a96c7Ip4jwNl7SHdjgpO1c74KLf9vvlyRYzTBgZM6muJROJHbSLtv0sLC3bjt2b82Aayj40FZeAd21RwomvjYJNpBqyIimrCOxG6dkqfRtFBhb37AAgkjcras2pOL04AWrgt8ikYlTbxUPan708ZhBno95gDdhTbNLy/kU0dNocUZB9/iLpeAKo5omw8OZ8WXq2ftx3UH0fhI9Xx+No4RQ+klY88="

before_install:
  - . ./tools/ci/before-install.sh

install:
  - . ./tools/ci/install.sh

before_script:
  - . ./tools/ci/before.sh

script:
  - . ./tools/ci/script.sh

before_cache:
  - . ./tools/ci/before-cache.sh

cache:
  directories:
     - .htd
     - .redo
     - ./node_modules
     - ./vendor
     - $HOME/.local
     - $HOME/.basher
     - $HOME/.cache/pip
     - $HOME/virtualenv
     - $HOME/.npm
     - $HOME/.composer
     - $HOME/.rvm/
     - $HOME/.statusdir/
     - $HOME/lib
     - $HOME/build/apenwarr
     - $HOME/build/ztombol
    # NOTE: careful not to include repo-under-test
     - $HOME/build/bvberkum/user-scripts-incubator
    # - $HOME/build/bvberkum/user-scripts
     - $HOME/build/user-tools/user-scripts
     - $HOME/build/user-tools/user-conf
     - $HOME/build/bvberkum/user-conf
     - $HOME/build/bvberkum/docopt-mpe
     - $HOME/build/bvberkum/git-versioning
     - $HOME/build/bats-core/bats-core
     #- $HOME/build/bvberkum/bats-...


after_failure:
  - . ./tools/ci/after-failure.sh
after_success:
  - . ./tools/ci/after-success.sh
after_script:
  - . ./tools/ci/after.sh


#matrix:
#  include:
#    - python: "2.7" # 2.7.14 [2018-12-07] 
#
#    - env: TRAVIS_US_PUBLISH="pre"
#      if: branch = r0.0
#
#    - env: TRAVIS_US_PUBLISH="rc"
#      if: branch = test

    #- python: 3.5
    #  if: branch = test

#    - if: branch = test
#      env: ENV_NAME=testing
#    branch = test
#      env: ENV_NAME=production
#  exclude: []

branches:
  only: []
  except: []

#deploy:

# Sync: X-CI-0.1:
# Id: /0.0 .travis.yml
