# Travis CI - test workflow </doc/dev/ci.md>
language: python
cache: pip
python:
  - 2.7
#addons:
#services: []
env:
  matrix: []
  global: []

#before_install: []
#  - test -n scriptpath=$(pwd) . build/init.sh
#install: []
before_script:
  - . .build/init.sh
script:
  #- lib_load build
  - test/lint.sh all
  - test/unit.sh all
  - test/spec.sh all
#after_script: []
#after_success: []
#after_failure: []
#before_cache:

#matrix:
#  include: []
#  exclude: []
#branches:
#  only: []
#  except: []
#deploy:
