# Travis CI - test workflow </doc/dev/ci.md>
language: python
python:
  - 2.7
addons:
  apt:
    packages:
      - realpath

#services: []
env:
  matrix: []
  global: []

#before_install: []
#  - test -n scriptpath=$(pwd) . build/init.sh
#install: []

before_script:
  - export scriptname='before-script' before_script_ts="$(date +%s)"
  - echo "Starting '$scriptname'..."
  - make init
  - bats --version

script:
  - export scriptname='script' script_ts="$(date +%s)"
  - echo "Starting '$scriptname'..."
  #- lib_load build
  - make test/baseline/realpath.tap
  #- make base
  - make lint
  #- make units
  #- make specs

#after_script: []
#after_success: []
#after_failure: []

before_cache:
  - export scriptname='before-cache' before_cache_ts="$(date +%s)"
  - echo "Starting '$scriptname'..."
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  directories:
     - ./node_modules
     - ./vendor
     - $HOME/.local
     - $HOME/.basher
     - $HOME/.cache/pip
     - $HOME/virtualenv
     - $HOME/.npm
     - $HOME/.composer
     - $HOME/.rvm/

#matrix:
#  include: []
#  exclude: []
#branches:
#  only: []
#  except: []
#deploy:
