# Travis CI - test workflow </doc/dev/ci.md>
language: python
python:
  - 2.7
addons:
  apt:
    packages:
      - realpath

#services: []
env:
  matrix: []
  global:
  - SRC_PREFIX=$HOME/build
  - VND_SRC_PREFIX=$HOME/build
  - VND_GH_SRC=$HOME/build
  - LOG=tools/sh/log.sh
  - CS=dark


before_install:
  - export scriptname='before-install' before_install_ts="$(date +%s)"
  #- scriptpath=$(pwd) . build/init.sh
  - . ./.htd/env.sh
install:
  - export scriptname='install' install_ts="$(date +%s)"
  - print_yellow "" "Starting '$scriptname'..."


before_script:
  - export scriptname='before-script' before_script_ts="$(date +%s)"
  - print_yellow "" "Starting '$scriptname'..."
  #- make init
script:
  - export scriptname='script' script_ts="$(date +%s)"
  - print_yellow "" "Starting '$scriptname'..."
# First smoke run everything with make
  #- lib_load build
  #- make test/baseline/realpath.tap
  - ./sh-test
  #- make base
  #- make lint
  #- make units
  #- make specs
# Cleanup and redo all
  #- git clean -dfx test/
  #- redo

#after_script: []
#after_success: []
#after_failure: []


before_cache:
  - export scriptname='before-cache' before_cache_ts="$(date +%s)"
  - print_yellow "" "Starting '$scriptname'..."
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  directories:
     - ./node_modules
     - ./vendor
     - $HOME/.local
     - $HOME/.basher
     - $HOME/.cache/pip
     - $HOME/virtualenv
     - $HOME/.npm
     - $HOME/.composer
     - $HOME/.rvm/

#matrix:
#  include: []
#  exclude: []
#branches:
#  only: []
#  except: []
#deploy:
