# Travis CI - test workflow </doc/dev/ci.md>

os: Linux
dist:
  - xenial

addons:
  apt:
    packages:
      - realpath

sudo: false

#services: []

#language: shell
language: python # Use Python build-env for NPM, PIP setup etc.
#python:
#  - "2.7" # 2.7.14 [2018-12-07] 

env:
  matrix: []
  global:
  - VND_SRC_PREFIX=$HOME/build
  - VND_GH_SRC=$VND_SRC_PREFIX
  - SRC_PREFIX=$VND_SRC_PREFIX
  - secure: enle3U9VEk9tkOgZLSzrOHRNQPAW/wHdC+0HfxjEAD70XUlpbrIJxRx9fX37E8+whj6KefNNw+B5L9dj8TTie+dah01uIw8Ypl6QbjgI8AtGbxlXzRf9q0brEc/03dYMd6zE3Jd5xN13dadB4D/0vtmrn06hBZqYcEze6RYauHvUq6NMPcvN5CnLXmyDcFWplDfoBk9RDMmt1+ccAC176+Z777+aX03IGQkgMOjxBhKMd4pT+A/8GLpIDjTsBRCAmIhfDqMkkAXYI0epEbORssQRAOHfDXlUP6EMZIbih2YLLbt6RzxMBauqxhcPRRKPKDvNfK42cf2RfVqNsRuuTZJrFMLNTuEBJcAhrcIa9dGb8ttMXxyom3VhDSb4natW8hPKDFSTfDlPXQZRBjcUC0I+NehIHLaX2umfKAWCopADYCmGbadMX2GBoDKUbTKFFuXpAJSel4umZZtR66Kyiq63w09gRVbRI86A4Wr2yBhZ7gs4Ey4LpCIql/v44tpbbt1FbHRyQ6+1ClVITucLG0aaCdDnPMhrHlkTZ7RnNd+wQZsE3cgUgkeGXlbahTrn2pmKetjzQnPwXF/KgcZlcyhkeJIaQZxLZ+rzlpaO6iILOmmYutAnzzLYUKponPjNUm45wIet1Hjgw771AOeGRMm/unQoQB2bIYhcbsLMxsM=


before_install:
  - . ./tools/ci/util.sh
  - export_stage before-install before_install && announce_stage
  - . ./tools/ci/env.sh

install:
  - export_stage install && announce_stage
  - ./.build.sh init
  - sh ./tools/ci/init.sh || echo err:$?
  #- make init

before_script:
  - export_stage before-script before_script && announce_stage

script:
  - export_stage script && announce_stage
  - . ./tools/ci/build.sh
# Smoke run everything with make
  #- make test/baseline/realpath.tap
  #- make base
  #- make lint
  #- make units
  #- make specs
# Cleanup and run again wtih redo
  #- git clean -dfx test/
  #- redo


before_cache:
  - export_stage before-cache before_cache && announce_stage
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  directories:
     - .htd
     - .redo
     - ./node_modules
     - ./vendor
     - $HOME/.local
     - $HOME/.basher
     - $HOME/.cache/pip
     - $HOME/virtualenv
     - $HOME/.npm
     - $HOME/.composer
     - $HOME/.rvm/
     - $HOME/.statusdir/
     - $HOME/lib
     - $HOME/build/apenwarr
     - $HOME/build/ztombol
    # NOTE: careful not to include repo-under-test
    # - $HOME/build/bvberkum/user-scripts
     - $HOME/build/user-tools/user-scripts
     - $HOME/build/user-tools/user-conf
     - $HOME/build/bvberkum/user-conf
     - $HOME/build/bvberkum/docopt-mpe
     - $HOME/build/bvberkum/git-versioning
     - $HOME/build/bats-core/bats-core
     #- $HOME/build/bvberkum/bats-...


after_failure:
  - export_stage failure && announce_stage
after_success:
  - export_stage success && announce_stage
after_script:
  - export_stage after && announce_stage
  - . ./tools/ci/parts/after.sh
  - . ./tools/ci/parts/publish.sh
  - announce "End of $scriptname"
  - echo Done


matrix:
  include:
    - python: 2.7

    - env: TRAVIS_US_PUBLISH="pre"
      if: branch = r0.0

    - env: TRAVIS_US_PUBLISH="rc"
      if: branch = test

    - python: 3.5
      if: branch = test

#    - if: branch = test
#      env: ENV_NAME=testing
#    branch = test
#      env: ENV_NAME=production

#  exclude: []
#branches:
#  only: []
#  except: []
#deploy:
