# Travis CI - test workflow </doc/dev/ci.md>
os: Linux
dist:
  - xenial

language: python
#language: shell
python:
  - "2.7" # 2.7.14 [2018-12-07] 
addons:
  apt:
    packages:
      - realpath

#services: []
env:
  matrix: []
  global:
  - SRC_PREFIX=$HOME/build
  - VND_SRC_PREFIX=$HOME/build
  - VND_GH_SRC=$HOME/build
  - secure: enle3U9VEk9tkOgZLSzrOHRNQPAW/wHdC+0HfxjEAD70XUlpbrIJxRx9fX37E8+whj6KefNNw+B5L9dj8TTie+dah01uIw8Ypl6QbjgI8AtGbxlXzRf9q0brEc/03dYMd6zE3Jd5xN13dadB4D/0vtmrn06hBZqYcEze6RYauHvUq6NMPcvN5CnLXmyDcFWplDfoBk9RDMmt1+ccAC176+Z777+aX03IGQkgMOjxBhKMd4pT+A/8GLpIDjTsBRCAmIhfDqMkkAXYI0epEbORssQRAOHfDXlUP6EMZIbih2YLLbt6RzxMBauqxhcPRRKPKDvNfK42cf2RfVqNsRuuTZJrFMLNTuEBJcAhrcIa9dGb8ttMXxyom3VhDSb4natW8hPKDFSTfDlPXQZRBjcUC0I+NehIHLaX2umfKAWCopADYCmGbadMX2GBoDKUbTKFFuXpAJSel4umZZtR66Kyiq63w09gRVbRI86A4Wr2yBhZ7gs4Ey4LpCIql/v44tpbbt1FbHRyQ6+1ClVITucLG0aaCdDnPMhrHlkTZ7RnNd+wQZsE3cgUgkeGXlbahTrn2pmKetjzQnPwXF/KgcZlcyhkeJIaQZxLZ+rzlpaO6iILOmmYutAnzzLYUKponPjNUm45wIet1Hjgw771AOeGRMm/unQoQB2bIYhcbsLMxsM=

before_install:
  - export scriptname='before-install' before_install_ts="$(date +%s)"
  #- scriptpath=$(pwd) . build/init.sh
  - . ./.htd/env.sh
install:
  - export scriptname='install' install_ts="$(date +%s)"
  - print_yellow "" "Starting '$scriptname'..."


before_script:
  - export scriptname='before-script' before_script_ts="$(date +%s)"
  - print_yellow "" "Starting '$scriptname'..."
  #- make init

script:
  - export scriptname='script' script_ts="$(date +%s)"
  - print_yellow "" "Starting '$scriptname'..."
# First smoke run everything with make
  #- lib_load build
  #- make test/baseline/realpath.tap
  - ./sh-test
  #- make base
  #- make lint
  #- make units
  #- make specs
# Cleanup and redo all
  #- git clean -dfx test/
  #- redo

#after_script: []
#after_success: []
#after_failure: []


before_cache:
  - export scriptname='before-cache' before_cache_ts="$(date +%s)"
  - print_yellow "" "Starting '$scriptname'..."
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  directories:
     - .htd
     - .redo
     - ./node_modules
     - ./vendor
     - $HOME/.local
     - $HOME/.basher
     - $HOME/.cache/pip
     - $HOME/virtualenv
     - $HOME/.npm
     - $HOME/.composer
     - $HOME/.rvm/
     - $HOME/.statusdir/
     - $HOME/lib
     - $HOME/build/apenwarr
     - $HOME/build/ztombol
     - $HOME/build/bvberkum/user-scripts
     - $HOME/build/bvberkum/user-conf
     - $HOME/build/bvberkum/docopt-mpe
     - $HOME/build/bvberkum/git-versioning
     - $HOME/build/bvberkum/bats-core

#matrix:
#  include: []
#  exclude: []
#branches:
#  only: []
#  except: []
#deploy:
