# Travis CI - test workflow </doc/dev/ci.md>

os: linux
dist:
  - xenial

addons:
  apt:
    packages:
      - realpath

sudo: false

services:
  - docker

language: shell
#language: python # Use Python build-env for NPM, PIP setup etc.

env:
  matrix: []
  global:
    - announce=1
    - VND_SRC_PREFIX=$HOME/build

before_install:
  - . ./tools/ci/before-install.sh

install:
  - . ./tools/ci/install.sh

before_script:
  - . ./tools/ci/before.sh

script:
  - . ./tools/ci/script.sh

before_cache:
  - . ./tools/ci/before-cache.sh

cache:
  directories:
     - .htd
     - .redo
     - ./node_modules
     - ./vendor
     - $HOME/.local
     - $HOME/.basher
     - $HOME/.cache/pip
     - $HOME/virtualenv
     - $HOME/.npm
     - $HOME/.composer
     - $HOME/.rvm/
     - $HOME/.statusdir/
     - $HOME/lib
     - $HOME/build/apenwarr
     - $HOME/build/ztombol
    # NOTE: careful not to include repo-under-test
     - $HOME/build/dotmpe/user-scripts-incubator
    # - $HOME/build/dotmpe/user-scripts
     - $HOME/build/user-tools/user-scripts
     - $HOME/build/user-tools/user-conf
     - $HOME/build/dotmpe/user-conf
     - $HOME/build/dotmpe/docopt-mpe
     - $HOME/build/dotmpe/git-versioning
     - $HOME/build/bats-core/bats-core
     #- $HOME/build/dotmpe/bats-...


after_failure:
  - . ./tools/ci/after-failure.sh
after_success:
  - . ./tools/ci/after-success.sh
after_script:
  - . ./tools/ci/after.sh


#matrix:
#  include:
#    - python: "2.7" # 2.7.14 [2018-12-07] 
#
#    - env: TRAVIS_US_PUBLISH="pre"
#      if: branch = r0.0
#
#    - env: TRAVIS_US_PUBLISH="rc"
#      if: branch = test

    #- python: 3.5
    #  if: branch = test

#    - if: branch = test
#      env: ENV_NAME=testing
#    branch = test
#      env: ENV_NAME=production
#  exclude: []

branches:
  only: []
  except: []

#deploy:

# Sync: X-CI-0.1:
# Id: /0.0 .travis.yml
