# Travis CI - test workflow </doc/dev/ci.md>

os: linux
dist:
  - xenial

addons:
  apt:
    packages:
      - realpath

sudo: false

services:
  - docker

language: shell
#language: python # Use Python build-env for NPM, PIP setup etc.

env:
  matrix: []
  global:
    - announce=1
    - VND_SRC_PREFIX=$HOME/build
    - LOG=$PWD/tools/sh/log.sh

# Travis has only options 'hB' on ($-) and the runner does not like unset'
before_install:
  - 'set -euo pipefail; . ./tools/ci/before-install.sh; set +euo pipefail;'

install:
  - 'set -euo pipefail; . ./tools/ci/install.sh; set +euo pipefail'

before_script:
  - 'set -euo pipefail; . ./tools/ci/before.sh; set +euo pipefail'

script:
  - 'sh_ci_script_status=; set -euo pipefail; . ./tools/ci/script.sh || sh_ci_script_status=$?; set +euo pipefail; return $sh_ci_script_status'

before_cache:
  - 'set -euo pipefail; . ./tools/ci/before-cache.sh; set +euo pipefail'

cache:
  directories:
     - .htd
     - .redo
     - ./node_modules
     - ./vendor
     - $HOME/.local
     - $HOME/.basher
     - $HOME/.cache/pip
     - $HOME/virtualenv
     - $HOME/.npm
     - $HOME/.composer
     - $HOME/.rvm/
     - $HOME/.statusdir/
     - $HOME/lib
     - $HOME/build/apenwarr
     - $HOME/build/ztombol
    # NOTE: careful not to include repo-under-test
     - $HOME/build/dotmpe/user-scripts-incubator
    # - $HOME/build/dotmpe/user-scripts
     - $HOME/build/user-tools/user-scripts
     - $HOME/build/user-tools/user-conf
     - $HOME/build/dotmpe/user-conf
     - $HOME/build/dotmpe/script-mpe
     - $HOME/build/dotmpe/docopt-mpe
     - $HOME/build/dotmpe/git-versioning
     - $HOME/build/bats-core/bats-core
     #- $HOME/build/dotmpe/bats-...

# Travis executes one: either 'after', or one of 'after-{failure,success}'
after_failure:
  - 'set -euo pipefail; . ./tools/ci/after-failure.sh; set +euo pipefail'
after_success:
  - 'set -euo pipefail; . ./tools/ci/after-success.sh; set +euo pipefail'
#after_script:
#  - 'set -euo pipefail; . ./tools/ci/after.sh; set +euo pipefail'


#matrix:
#  include:
#    - python: "2.7" # 2.7.14 [2018-12-07] 
#
#    - env: TRAVIS_US_PUBLISH="pre"
#      if: branch = r0.0
#
#    - env: TRAVIS_US_PUBLISH="rc"
#      if: branch = test

    #- python: 3.5
    #  if: branch = test

#    - if: branch = test
#      env: ENV_NAME=testing
#    branch = test
#      env: ENV_NAME=production
#  exclude: []

branches:
  only: []
  except: []

#deploy:

# Sync: X-CI-0.1:
# Id: U-S:.travis.yml
