jobs:
  build:
    # Circle CI (base image):
    # Each command line is run in `/bin/bash -eo pipefail`.
    # The start dir is ~/project, there is a helper to create the checkout
    docker:
      - image: cimg/base:2020.01
    steps:

    - run: sudo apt-get update && sudo apt-get install -y bc uuid-runtime moreutils curl renameutils virtualenv

    - checkout
    - run:
        name: Move checkout
        command: |
            echo "$(whoami)@$(hostname -f):$PWD"; cd; \
            mv ~/project/ ~/user-scripts; \
            mkdir ~/project; \
            mv ~/user-scripts/ ~/project/; \
            ln -s ~/project/user-scripts ~/bin; \
            cd ~/project/user-scripts

    - run:
        name: Build
        command: |
            cd ~/project/user-scripts; \
            set -euo pipefail; \
            export TERM=xterm \
              VND_SRC_PREFIX=$HOME/build \
              U_S=$PWD \
              ENV_DEV=1 \
              CS=dark \
              CTX_PID=$$ \
              CTX_P= \
              ;
            ./sh-ci

# Id: U-S:circleci/config.yml
